/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.accountingmanagement;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.*;

/**
 *
 * @author nagihan_imamoğlu
 */
public class AddFrame extends javax.swing.JFrame {

    DefaultListModel<String> category = new DefaultListModel<>();
    private int user_id;
    private String username_surname;
    boolean darkMode = false;

    /**
     * Creates new form AddFrame
     */
    public AddFrame() {
        initComponents();
    }

    public AddFrame(int id, String username_surname) {
        initComponents();
        this.user_id = id;
        this.username_surname = username_surname;

        Label6.setVisible(false);
        category.addElement("rent");
        category.addElement("salary");
        category.addElement("services");
        category.addElement("food");
        category.addElement("transportation");
        List.setModel(category);

        TypeBox.removeAllItems();
        TypeBox.addItem("income");
        TypeBox.addItem("expense");
        TypeBox.setSelectedIndex(-1);
        CurrencyBox.removeAllItems();
        CurrencyBox.addItem("TL");
        CurrencyBox.addItem("USD");
        CurrencyBox.addItem("EURO");
        CurrencyBox.setSelectedIndex(-1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Label1 = new javax.swing.JLabel();
        Label2 = new javax.swing.JLabel();
        Label3 = new javax.swing.JLabel();
        Label4 = new javax.swing.JLabel();
        Label5 = new javax.swing.JLabel();
        SaveButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        TypeBox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        List = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextArea = new javax.swing.JTextArea();
        Amount = new javax.swing.JSpinner();
        CurrencyBox = new javax.swing.JComboBox<>();
        Label6 = new javax.swing.JLabel();
        ModeButton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        Label1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        Label1.setForeground(new java.awt.Color(51, 51, 51));
        Label1.setText("TYPE:");

        Label2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        Label2.setForeground(new java.awt.Color(51, 51, 51));
        Label2.setText("CATEGORY:");

        Label3.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        Label3.setForeground(new java.awt.Color(51, 51, 51));
        Label3.setText("AMOUNT:");

        Label4.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        Label4.setForeground(new java.awt.Color(51, 51, 51));
        Label4.setText("DESCRIPTION:");

        Label5.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        Label5.setForeground(new java.awt.Color(51, 51, 51));
        Label5.setText("CURRENCY:");

        SaveButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SaveButton.setForeground(new java.awt.Color(51, 51, 51));
        SaveButton.setText("SAVE");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        BackButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BackButton.setForeground(new java.awt.Color(51, 51, 51));
        BackButton.setText("BACK");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        TypeBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        List.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(List);

        TextArea.setColumns(20);
        TextArea.setRows(5);
        jScrollPane2.setViewportView(TextArea);

        CurrencyBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Label6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Label6.setForeground(new java.awt.Color(255, 0, 0));
        Label6.setText("*Please fill in  all required fields!");

        ModeButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ModeButton.setForeground(new java.awt.Color(51, 51, 51));
        ModeButton.setText("Dark/Light Mode");
        ModeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Label2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Label4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TypeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(53, 53, 53)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Label5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Label3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Amount)
                                    .addComponent(CurrencyBox, 0, 90, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Label6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SaveButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BackButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ModeButton)))
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label1)
                    .addComponent(TypeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label3)
                    .addComponent(Amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label2)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Label5)
                        .addComponent(CurrencyBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label4)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label6)
                    .addComponent(SaveButton))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BackButton)
                    .addComponent(ModeButton))
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        // TODO add your handling code here:
        if (Amount.getValue() == null || TypeBox.getSelectedItem() == null || CurrencyBox.getSelectedItem() == null || List.getSelectedValue() == null) {
            Label6.setVisible(true);
            return;
        }

        String type = TypeBox.getSelectedItem().toString();
        String category = List.getSelectedValue();
        float amount = Float.parseFloat(Amount.getValue().toString());
        String description = TextArea.getText();
        String currency = CurrencyBox.getSelectedItem().toString();
        int user_id = this.user_id;
        String username_surname = this.username_surname;
        
        if(amount <= 0){
            JOptionPane.showMessageDialog(null,"Amount must be positive!");
            return;
        }

        if (UserTransactions.addTransaction(type, category, amount, description, user_id, username_surname, currency)) {
            JOptionPane.showMessageDialog(null, "Transaction added successfully!");
            TypeBox.setSelectedIndex(0);
            List.setSelectedIndex(0);
            Amount.setValue(0);
            TextArea.setText("");
            CurrencyBox.setSelectedIndex(0);
            Label6.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(null, "Transaction is failed!");
        }
    }//GEN-LAST:event_SaveButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new UserFrame(user_id, username_surname).setVisible(true);
    }//GEN-LAST:event_BackButtonActionPerformed

    private void ModeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModeButtonActionPerformed
        // TODO add your handling code here:
        if (!darkMode) {
            DarkLight<JPanel> panel = new DarkLight<>();
            DarkLight<JLabel> label = new DarkLight<>();
            DarkLight<JButton> button = new DarkLight<>();
            DarkLight<JRadioButton> radiobutton = new DarkLight<>();

            panel.DarkMode(jPanel1);
            label.DarkMode(Label1);
            label.DarkMode(Label2);
            label.DarkMode(Label3);
            label.DarkMode(Label4);
            label.DarkMode(Label5);
            button.DarkMode(BackButton);
            button.DarkMode(SaveButton);
            radiobutton.DarkMode(ModeButton);

            darkMode = true;
        } else {
            DarkLight<JPanel> panel = new DarkLight<>();
            DarkLight<JLabel> label = new DarkLight<>();
            DarkLight<JButton> button = new DarkLight<>();
            DarkLight<JRadioButton> radiobutton = new DarkLight<>();

            panel.LightMode(jPanel1);
            label.LightMode(Label1);
            label.LightMode(Label2);  
            label.DarkMode(Label3);
            label.DarkMode(Label4);
            label.DarkMode(Label5);
            button.DarkMode(BackButton);
            button.DarkMode(SaveButton);
            radiobutton.LightMode(ModeButton);

            darkMode = false;
        }
    }//GEN-LAST:event_ModeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner Amount;
    private javax.swing.JButton BackButton;
    private javax.swing.JComboBox<String> CurrencyBox;
    private javax.swing.JLabel Label1;
    private javax.swing.JLabel Label2;
    private javax.swing.JLabel Label3;
    private javax.swing.JLabel Label4;
    private javax.swing.JLabel Label5;
    private javax.swing.JLabel Label6;
    private javax.swing.JList<String> List;
    private javax.swing.JRadioButton ModeButton;
    private javax.swing.JButton SaveButton;
    private javax.swing.JTextArea TextArea;
    private javax.swing.JComboBox<String> TypeBox;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
