/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.accountingmanagement;

import java.sql.*;
import javax.swing.*;

/**
 *
 * @author nagihan_imamoğlu
 */
public class LoginFrame extends javax.swing.JFrame {

    private static final String connectionString = "jdbc:mysql://localhost:3306/accountingmanagement?user=root&password=";
    boolean darkMode = false;
    int user_id;
    String username_surname;

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
        this.user_id = user_id;
        this.username_surname = username_surname;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Label1 = new javax.swing.JLabel();
        Label2 = new javax.swing.JLabel();
        Label3 = new javax.swing.JLabel();
        Label4 = new javax.swing.JLabel();
        TextName = new javax.swing.JTextField();
        LoginButton = new javax.swing.JButton();
        ModeButton = new javax.swing.JRadioButton();
        TextPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        Label1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Label1.setForeground(new java.awt.Color(51, 51, 51));
        Label1.setText("Accounting Management System");

        Label2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Label2.setForeground(new java.awt.Color(51, 51, 51));
        Label2.setText("User Login Screen");

        Label3.setForeground(new java.awt.Color(51, 51, 51));
        Label3.setText("Your Username");

        Label4.setForeground(new java.awt.Color(51, 51, 51));
        Label4.setText("Your Password");

        TextName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextNameActionPerformed(evt);
            }
        });

        LoginButton.setBackground(new java.awt.Color(51, 51, 51));
        LoginButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LoginButton.setForeground(new java.awt.Color(255, 255, 255));
        LoginButton.setText("Log In");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });

        ModeButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ModeButton.setForeground(new java.awt.Color(51, 51, 51));
        ModeButton.setText("Dark/Light Mode");
        ModeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModeButtonActionPerformed(evt);
            }
        });

        TextPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextPasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(Label1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(LoginButton)
                            .addComponent(Label2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(TextName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TextPassword, javax.swing.GroupLayout.Alignment.LEADING))))
                .addContainerGap(118, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ModeButton)
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(Label1)
                .addGap(30, 30, 30)
                .addComponent(Label2)
                .addGap(18, 18, 18)
                .addComponent(Label3)
                .addGap(18, 18, 18)
                .addComponent(TextName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Label4)
                .addGap(18, 18, 18)
                .addComponent(TextPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(LoginButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(ModeButton)
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ModeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModeButtonActionPerformed
        // TODO add your handling code here:

        if (!darkMode) {
            DarkLight<JPanel> panel = new DarkLight<>();
            DarkLight<JLabel> label = new DarkLight<>();
            DarkLight<JButton> button = new DarkLight<>();
            DarkLight<JRadioButton> radiobutton = new DarkLight<>();

            panel.DarkMode(jPanel1);
            label.DarkMode(Label1);
            label.DarkMode(Label2);
            label.DarkMode(Label3);
            label.DarkMode(Label4);
            button.DarkMode(LoginButton);
            radiobutton.DarkMode(ModeButton);

            darkMode = true;
        } else {
            DarkLight<JPanel> panel = new DarkLight<>();
            DarkLight<JLabel> label = new DarkLight<>();
            DarkLight<JButton> button = new DarkLight<>();
            DarkLight<JRadioButton> radiobutton = new DarkLight<>();

            panel.LightMode(jPanel1);
            label.LightMode(Label1);
            label.LightMode(Label2);
            label.LightMode(Label3);
            label.LightMode(Label4);
            button.LightMode(LoginButton);
            radiobutton.LightMode(ModeButton);

            darkMode = false;
        }
    }//GEN-LAST:event_ModeButtonActionPerformed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        // TODO add your handling code here:
        String username = TextName.getText();
        String password = new String(TextPassword.getPassword());

        if (username.trim().isEmpty() || password.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please fill in the blanks!");
            return;
        } else {
            String sql = "SELECT id, role, name_surname FROM users WHERE email = ? AND password = ?";

            try (
                    Connection connection = DriverManager.getConnection(connectionString); 
                    PreparedStatement statement = connection.prepareStatement(sql);
                ) {
                statement.setString(1, username);
                statement.setString(2, password);
                ResultSet rs = statement.executeQuery();

                if (rs.next()) {      
                    
                    int user_id = rs.getInt("id");
                    String role = rs.getString("role");
                    String fullname = rs.getString("name_surname");

                    if (role.equals("admin")) {
                        AdminFrame adminFrame = new AdminFrame(user_id,fullname);
                        adminFrame.setVisible(true);
                    } else {
                        UserFrame userFrame = new UserFrame(user_id, fullname);
                        userFrame.setVisible(true);
                    }
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Your username or password is incorrect!");
                }
            } catch (Exception ex) {
                System.out.println("Warning;" + ex.getMessage());
            }
        }
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void TextPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextPasswordActionPerformed

    private void TextNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label1;
    private javax.swing.JLabel Label2;
    private javax.swing.JLabel Label3;
    private javax.swing.JLabel Label4;
    private javax.swing.JButton LoginButton;
    private javax.swing.JRadioButton ModeButton;
    private javax.swing.JTextField TextName;
    private javax.swing.JPasswordField TextPassword;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
