/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.accountingmanagement;

import java.io.FileWriter;
import java.io.IOException;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.time.LocalDate;
import javax.swing.JOptionPane;
/**
 *
 * @author nagihan_imamoğlu
 */
public class ReportsFrame extends javax.swing.JFrame {
    
private static final String connectionString = "jdbc:mysql://localhost:3306/accountingmanagement?user=root&password=";
    /**
     * Creates new form ReportsFrame
     */
    int user_id;
    String username_surname;
    
    public ReportsFrame() {
        initComponents();
        loadReports();
    }
    
    public ReportsFrame(int user_id, String username_surname) {
        initComponents();
        this.user_id = user_id;
        this.username_surname = username_surname;
        loadReports();
    }
    
    
    public void loadReports(){
        DefaultTableModel model = new DefaultTableModel(new String[]{
            "Id","Name Surname","Total Income","Total Expense","Net Balance"},0);
        Table.setModel(model);
        
        String usersQuery = "SELECT id, name_surname FROM users";
        String incomeQuery = "SELECT SUM(amount) FROM transactions WHERE user_id = ? AND type = ?";
        String expenseQuery = "SELECT SUM(amount) FROM transactions WHERE user_id = ? AND type = ?";
        
        try(
               Connection connection = DriverManager.getConnection(connectionString);
               PreparedStatement stUsers = connection.prepareStatement(usersQuery);
                PreparedStatement stIncome = connection.prepareStatement(incomeQuery);
                PreparedStatement stExpense = connection.prepareStatement(expenseQuery);
                ResultSet rsUsers = stUsers.executeQuery()
                ){
            while(rsUsers.next()){
                int id = rsUsers.getInt("id");
                String nameSurname = rsUsers.getString("name_surname");
                
                stIncome.setInt(1, id);
                stIncome.setString(2, "income");
                
                stExpense.setInt(1, id);
                stExpense.setString(2, "expense");
                
                ResultSet rsIncome = stIncome.executeQuery();
                ResultSet rsExpense = stExpense.executeQuery();
                
                float income = 0, expense = 0;
                if(rsIncome.next()){
                    income = rsIncome.getFloat(1);
                }
                if(rsExpense.next()){
                    expense = rsExpense.getFloat(1);
                }
                float balance = income - expense;
                
                model.addRow(new Object[]{id,nameSurname,income,expense,balance});
            }
        } catch(SQLException e){
            JOptionPane.showMessageDialog(null,"Database error: " + e.getMessage());
        }   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        BackButton = new javax.swing.JButton();
        ExportButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Table);

        BackButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BackButton.setForeground(new java.awt.Color(51, 51, 51));
        BackButton.setText("BACK");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        ExportButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ExportButton.setForeground(new java.awt.Color(51, 51, 51));
        ExportButton.setText("EXPORT");
        ExportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExportButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(BackButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ExportButton)
                .addGap(32, 32, 32))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BackButton)
                    .addComponent(ExportButton))
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExportButtonActionPerformed
        // TODO add your handling code here:
        try{                     
            FileWriter writer = new FileWriter("AllFinancialReport_" + "_" + LocalDate.now() + ".txt");
            writer.write("Financial Reports (" + LocalDate.now() + ")\n\n");
            
            for(int i = 0; i < Table.getRowCount(); i++){
                String username = Table.getValueAt(i, 1).toString();
                String income = Table.getValueAt(i, 2).toString();
                String expense = Table.getValueAt(i, 3).toString();
                String balance = Table.getValueAt(i, 4).toString();
                
                writer.write(username + "\n");
                writer.write("Income: " + income + "TL\n");
                writer.write("Expense: " + expense + "TL\n");
                writer.write("Balance: " + balance + "TL\n");     
            }
            writer.close();
            JOptionPane.showMessageDialog(null, "Reports exported successfully!");
        }catch(IOException e){
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_ExportButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new AdminFrame().setVisible(true);
    }//GEN-LAST:event_BackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReportsFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton ExportButton;
    private javax.swing.JTable Table;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
