/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.accountingmanagement;

//import javax.swing.table.DefaultTableModel;

import javax.swing.*;
/**
 *
 * @author nagihan_imamoğlu
 */
public class UserFrame extends javax.swing.JFrame {

    int user_id;
    String username_surname;
    boolean darkMode = false;
    
    /**
     * Creates new form UserFrame
     */
    public UserFrame() {
        initComponents();   
    }
    
    public UserFrame(int user_id, String username_surname){
        initComponents();
        this.user_id = user_id;
        this.username_surname = username_surname;
        Label1.setText("Welcome, " + username_surname);     
    }
    
//    public DefaultTableModel loadTransactions(){
//        return UserTransactions.accessTransactions(user_id);
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ModeButton = new javax.swing.JRadioButton();
        BackButton = new javax.swing.JButton();
        Label1 = new javax.swing.JLabel();
        Label2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Transactions = new javax.swing.JMenu();
        AddItem = new javax.swing.JMenuItem();
        Delete_EditItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        ViewItem = new javax.swing.JMenuItem();
        Reports = new javax.swing.JMenu();
        ReportsItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        ModeButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ModeButton.setForeground(new java.awt.Color(51, 51, 51));
        ModeButton.setText("Dark/Light Mode");
        ModeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModeButtonActionPerformed(evt);
            }
        });

        BackButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BackButton.setForeground(new java.awt.Color(51, 51, 51));
        BackButton.setText("BACK");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        Label1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        Label1.setForeground(new java.awt.Color(51, 51, 51));
        Label1.setText("Welcome, USER");

        Label2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        Label2.setForeground(new java.awt.Color(51, 51, 51));
        Label2.setText("From this screen you can choose to add, delete, update, and view your transactions.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(BackButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 274, Short.MAX_VALUE)
                .addComponent(ModeButton)
                .addGap(15, 15, 15))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Label2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(Label1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Label2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ModeButton)
                    .addComponent(BackButton))
                .addGap(24, 24, 24))
        );

        Transactions.setForeground(new java.awt.Color(51, 51, 51));
        Transactions.setText("Transactions");
        Transactions.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        AddItem.setText("Add");
        AddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddItemActionPerformed(evt);
            }
        });
        Transactions.add(AddItem);

        Delete_EditItem.setText("Delete/Edit");
        Delete_EditItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_EditItemActionPerformed(evt);
            }
        });
        Transactions.add(Delete_EditItem);
        Transactions.add(jSeparator1);

        ViewItem.setText("View");
        ViewItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewItemActionPerformed(evt);
            }
        });
        Transactions.add(ViewItem);

        jMenuBar1.add(Transactions);

        Reports.setForeground(new java.awt.Color(51, 51, 51));
        Reports.setText("Reports");
        Reports.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        ReportsItem.setText("My reports");
        ReportsItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportsItemActionPerformed(evt);
            }
        });
        Reports.add(ReportsItem);

        jMenuBar1.add(Reports);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ModeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModeButtonActionPerformed
        // TODO add your handling code here:
        if (!darkMode) {
            DarkLight<JPanel> panel = new DarkLight<>();
            DarkLight<JLabel> label = new DarkLight<>();
            DarkLight<JButton> button = new DarkLight<>();
            DarkLight<JRadioButton> radiobutton = new DarkLight<>();

            panel.DarkMode(jPanel1);
            label.DarkMode(Label1);
            label.DarkMode(Label2);            
            button.DarkMode(BackButton);
            radiobutton.DarkMode(ModeButton);

            darkMode = true;
        } else {
            DarkLight<JPanel> panel = new DarkLight<>();
            DarkLight<JLabel> label = new DarkLight<>();
            DarkLight<JButton> button = new DarkLight<>();
            DarkLight<JRadioButton> radiobutton = new DarkLight<>();

            panel.LightMode(jPanel1);
            label.LightMode(Label1);
            label.LightMode(Label2);            
            button.LightMode(BackButton);
            radiobutton.LightMode(ModeButton);

            darkMode = false;
        }
    }//GEN-LAST:event_ModeButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new LoginFrame().setVisible(true);
    }//GEN-LAST:event_BackButtonActionPerformed

    private void AddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddItemActionPerformed
        // TODO add your handling code here:
        AddFrame addTransaction = new AddFrame(this.user_id, this.username_surname);
        addTransaction.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AddItemActionPerformed

    private void Delete_EditItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_EditItemActionPerformed
        // TODO add your handling code here:
        Delete_EditFrame delete_editTransactions = new Delete_EditFrame(this.user_id, this.username_surname);
        delete_editTransactions.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Delete_EditItemActionPerformed

    private void ViewItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewItemActionPerformed
        // TODO add your handling code here:
        ViewFrame view = new ViewFrame(this.user_id, this.username_surname);
        view.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ViewItemActionPerformed

    private void ReportsItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportsItemActionPerformed
        // TODO add your handling code here:
        float[] summary = UserTransactions.accessFinancialSummary(user_id);
        float income = summary[0];
        float expense = summary[1];
        new UserReportsFrame(user_id, username_surname, income, expense).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ReportsItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AddItem;
    private javax.swing.JButton BackButton;
    private javax.swing.JMenuItem Delete_EditItem;
    private javax.swing.JLabel Label1;
    private javax.swing.JLabel Label2;
    private javax.swing.JRadioButton ModeButton;
    private javax.swing.JMenu Reports;
    private javax.swing.JMenuItem ReportsItem;
    private javax.swing.JMenu Transactions;
    private javax.swing.JMenuItem ViewItem;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
